version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: hr-postgres
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_pass
      POSTGRES_DB: hr_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  trino:
    image: trinodb/trino:latest
    container_name: hr-trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config/catalog:/etc/trino/catalog
    depends_on:
      - postgres
      - elasticsearch

  ontop:
    image: ontop/ontop
    container_name: hr-ontop
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/hr-documents.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/hr-mapping.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/trino.properties
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    ports:
      - "8081:8080"
    depends_on:
      - trino

volumes:
  pgdata:
  esdata:
